<?php $config = \Suggestotron\Config::get('site'); ?>
<!doctype html>
<html>
<head>
    <title><?php echo $config["title"];?></title>
    <link rel="stylesheet" type="text/css" href="/sugestron/public/css/bootstrap.min.css">
    <script type="text/javascript" src="/sugestron/public/js/jquery.min.js"></script>
    <script type="text/javascript" src="/sugestron/public/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="/sugestron/public">Suggestotron</a>
        </div>
        <form class="navbar-form navbar-right" role="search">
            <a href="add" class="btn btn-default">
                <span class="glyphicon glyphicon-plus-sign"></span>
                Add Topic
            </a>
        </form>
    </div>
</nav>

<div class="container">
    <!-- Specific Page Content Goes Here -->
    <?php $this->content(); ?>
</div>
<script type="text/javascript">
    $('[data-toggle="popover"]').popover();
</script>
</body>
</html>