<?php
$topics = $this->topics;
foreach ($topics as $topic) {
    ?>
    <section>
        <div class="row">
            <div class="col-xs-12">
                <h3><?=$topic['title'];?></h3>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-8">
                <p class="text-muted">
                    <?=nl2br($topic['description']);?>
                </p>
            </div>
            <div class="col-xs-4">
                <p class="pull-right">
                    <a href="/vote/up/<?=$topic['id']; ?>" class="btn btn-success">
                        <span class="glyphicon glyphicon-arrow-up">
                            <strong><?=(isset($topic['count'])) ? $topic['count'] : 0;?></strong>
                        </span>
                    </a>
                    <a href="/vote/down/<?=$topic['id']; ?>" class="btn btn-warning">
                        <span class="glyphicon glyphicon-arrow-down"></span>
                    </a>
                    <a href="/topic/edit/<?=$topic['id']; ?>" class="btn btn-primary">
                        <span class="glyphicon glyphicon-edit">
                            <strong>Edit</strong>
                        </span>
                    </a>
                    <a href="/topic/delete/<?=$topic['id']; ?>" class="btn btn-danger" data-container="body"
                       data-toggle="popover" data-trigger="hover" data-placement="top" data-title="Are you sure?"
                       data-content=" This cannot be undone!">
                        <span class="glyphicon glyphicon-remove">

                        </span>
                     </a>

                </p>
            </div>
        </div>

    </section>
    <hr>

    <?php
}
?>
<a href="/about">About this.</a>